// This code was automatically generated by GenHeader.py
#pragma once
#include "JamUtil.h"

// Forward declare the asset array
extern JULoadedAsset ASSETS[17];

#ifdef NYMASSETS_IMPLEMENTATION
JULoadedAsset ASSETS[] = {
    {"data/Sprites.ini"},
    {"data/fonts/TNR16.jufnt"},
    {"data/fonts/UbuntuMono16.jufnt"},
    {"data/sprites/MenuOptionsButton.png"},
    {"data/sprites/MenuPlayButton.png"},
    {"data/sprites/MenuQuitButton.png"},
    {"data/sprites/MessageBoxConfirmButton.png"},
    {"data/sprites/Player1Idle.png"},
    {"data/sprites/Player1Running.png"},
    {"data/textures/MenuBackground.png"},
    {"data/textures/MessageBoxBackground.png"},
    {"data/sprites/MenuPlayButton.png", 0, 0, 112, 32, 0, 3, 0, 0},
    {"data/sprites/MenuOptionsButton.png", 0, 0, 112, 32, 0, 3, 0, 0},
    {"data/sprites/MenuQuitButton.png", 0, 0, 112, 32, 0, 3, 0, 0},
    {"data/sprites/MessageBoxConfirmButton.png", 0, 0, 32, 16, 0, 3, 0, 0},
    {"data/sprites/Player1Idle.png", 0, 0, 16, 16, 4, 4, 0, 0},
    {"data/sprites/Player1Running.png", 0, 0, 16, 16, 4, 4, 0, 0},
};
#endif

typedef struct NymAssets {
    JULoader loader;
    JUBuffer bufSprites;
    JUFont fntTNR16;
    JUFont fntUbuntuMono16;
    VK2DTexture texMenuOptionsButton;
    VK2DTexture texMenuPlayButton;
    VK2DTexture texMenuQuitButton;
    VK2DTexture texMessageBoxConfirmButton;
    VK2DTexture texPlayer1Idle;
    VK2DTexture texPlayer1Running;
    VK2DTexture texMenuBackground;
    VK2DTexture texMessageBoxBackground;
    JUSprite sprMenuPlayButton;
    JUSprite sprMenuOptionsButton;
    JUSprite sprMenuQuitButton;
    JUSprite sprMessageBoxConfirmButton;
    JUSprite sprPlayer1Idle;
    JUSprite sprPlayer1Running;
} NymAssets;

// Functions to create and destroy the asset struct
NymAssets *buildNymAssets();
void destroyNymAssets(NymAssets *s);

#ifdef NYMASSETS_IMPLEMENTATION
NymAssets *buildNymAssets() {
    NymAssets *s = malloc(sizeof(struct NymAssets));
    s->loader = juLoaderCreate(ASSETS, 17);
    s->bufSprites = juLoaderGetBuffer(s->loader, "data/Sprites.ini");
    s->fntTNR16 = juLoaderGetFont(s->loader, "data/fonts/TNR16.jufnt");
    s->fntUbuntuMono16 = juLoaderGetFont(s->loader, "data/fonts/UbuntuMono16.jufnt");
    s->texMenuOptionsButton = juLoaderGetTexture(s->loader, "data/sprites/MenuOptionsButton.png");
    s->texMenuPlayButton = juLoaderGetTexture(s->loader, "data/sprites/MenuPlayButton.png");
    s->texMenuQuitButton = juLoaderGetTexture(s->loader, "data/sprites/MenuQuitButton.png");
    s->texMessageBoxConfirmButton = juLoaderGetTexture(s->loader, "data/sprites/MessageBoxConfirmButton.png");
    s->texPlayer1Idle = juLoaderGetTexture(s->loader, "data/sprites/Player1Idle.png");
    s->texPlayer1Running = juLoaderGetTexture(s->loader, "data/sprites/Player1Running.png");
    s->texMenuBackground = juLoaderGetTexture(s->loader, "data/textures/MenuBackground.png");
    s->texMessageBoxBackground = juLoaderGetTexture(s->loader, "data/textures/MessageBoxBackground.png");
    s->sprMenuPlayButton = juLoaderGetSprite(s->loader, "data/sprites/MenuPlayButton.png");
    s->sprMenuOptionsButton = juLoaderGetSprite(s->loader, "data/sprites/MenuOptionsButton.png");
    s->sprMenuQuitButton = juLoaderGetSprite(s->loader, "data/sprites/MenuQuitButton.png");
    s->sprMessageBoxConfirmButton = juLoaderGetSprite(s->loader, "data/sprites/MessageBoxConfirmButton.png");
    s->sprPlayer1Idle = juLoaderGetSprite(s->loader, "data/sprites/Player1Idle.png");
    s->sprPlayer1Running = juLoaderGetSprite(s->loader, "data/sprites/Player1Running.png");
    return s;
}

void destroyNymAssets(NymAssets *s) {
    juLoaderFree(s->loader);
    free(s);
}
#endif
